config/routes.rb
Rails.application.routes.draw do


  get 'pages/result'

  get 'products/laos'
  get 'products/thai'


  resources :bet_types
  get 'admin/index'
  get 'admin/rounds'
  get 'admin/requests'
  get 'admin/transactions'
  get 'admin/users'
  get 'admin/stats'
  get 'admin/notification'
  get 'admin/bypass'
  get 'admin/resetpwd'

  resources :transactions
  resources :rounds

  post 'rounds/calculate'
  post 'rounds/process1688'

  resources :requests do
    get 'confirm(.:format)' => 'requests#confirm'
    get 'cancel(.:format)' => 'requests#cancel'
  end
  get 'pages/index'
  get 'pages/faq'
  get 'pages/odd_table'
  root 'products#index'
  get 'products/thai'
  get 'products/laos'
  get 'products/index'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '*path' => redirect('/')
end

app/controllers/bet_types_controller.rb
class BetTypesController < ApplicationController
  before_action :set_bet_type, only: %i[show edit update destroy]
  before_action :authenticate_admin

  # GET /bet_types
  # GET /bet_types.json
  def index
    @bet_types = BetType.all.order_by(created_at: 'desc')
  end

  # GET /bet_types/1
  # GET /bet_types/1.json
  def show; end

  # GET /bet_types/new
  def new
    @bet_type = BetType.new
    @bet_type_list = { 'b31' => '3ตัวบน',
                       'b32' => '3ตัวโต๊ด',
                       'b33' => '3ตัวล่าง',
                       'b34' => '3ตัวหน้า',
                       'b21' => '2ตัวบน',
                       'b22' => '2ตัวล่าง',
                       'b23' => '2ตัวโต๊ด',
                       'b11' => 'วิ่งบน',
                       'b12' => 'วิ่งล่าง' }
    @bet_type['id'] = "new"
  end

  # GET /bet_types/1/edit
  def edit
    @bet_type_list = { 'b31' => '3ตัวบน',
                       'b32' => '3ตัวโต๊ด',
                       'b33' => '3ตัวล่าง',
                       'b34' => '3ตัวหน้า',
                       'b21' => '2ตัวบน',
                       'b22' => '2ตัวล่าง',
                       'b23' => '2ตัวโต๊ด',
                       'b11' => 'วิ่งบน',
                       'b12' => 'วิ่งล่าง' }
  end

  # POST /bet_types
  # POST /bet_types.json
  def create
    @b = bet_type_params
    logger.debug "@b: #{@b}"
    @bet_type = BetType.new(bet_type_params)
    @res = BetType.where(product: params[:_json][0][:product])

    respond_to do |format|
      if @res.count == 0 && @bet_type.save
        format.json { render json: {"msg": "บันทึกสำเร็จ"}, status: :ok, location: @bet_type }
      else
        format.json { render json: {"msg": "บันทึกไม่สำเร็จ"}, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bet_types/1
  # PATCH/PUT /bet_types/1.json
  def update
    respond_to do |format|
      if @bet_type.update(bet_type_params)
        format.json { render json: {"msg": "บันทึกสำเร็จ"}, status: :ok, location: @bet_type }
      else
        format.json { render json: {"msg": "บันทึกไม่สำเร็จ"}, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bet_types/1
  # DELETE /bet_types/1.json
  def destroy
    @bet_type.destroy
    respond_to do |format|
      format.html { redirect_to bet_types_url, notice: 'Bet type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def authenticate_admin
    if !(user_signed_in? && current_user.username == '168899')
      redirect_to root_path
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_bet_type
    @bet_type = BetType.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def bet_type_params
    b_params = params[:_json][0]

    b_params = b_params.as_json

    b_params
  end
end

app/helpers/bet_types_helper.rb
module BetTypesHelper
end

app/views/bet_types/_form.html.erb
<form>
  <%= csrf_meta_tag %>

  <input class="form-control" type="text" id="bet_type_id" value="<%= @bet_type['id'] %>" hidden><br/>

  <div class="form-group row">
    <label class="col-md-3 col-form-label" for="l10">หวย :</label>
    <div class="col-md-6">
      <div class="input-group">

        <select name="product" id="product" class="form-control" autofocus="autofocus">
          <option value="หวยลาว" <%= @bet_type['product'] == "หวยลาว" ? "selected" : "" %>>หวยลาว</option>
          <option value="หวยไทย" <%= @bet_type['product'] == "หวยไทย" ? "selected" : "" %>>หวยไทย</option>
        </select>

      </div>
    </div>
  </div>

  <div>
    <table class="table table-responsive">
      <thead>
        <tr class="bg-primary text-inverse">
          <th>ประเภท</th>
          <th>แต้มต่อ</th>
          <th>ความเสี่ยงสูงสุด (บาท)</th>

        </tr>
      </thead>
      <tbody>
        <% @bet_type_list.each do |k, v| %>
        <tr>
          <td>
            <%=v%>
            <input class="form-control" type="text" id="<%= k %>_name" value="<%=v%>" hidden>
          </td>
          <% if @bet_type['id'] == "new" %>
          <td>
            <input class="form-control" type="number" id="<%= k %>_odd" value=""><br/>
          </td>
          <td>
            <input class="form-control" type="number" id="<%= k %>_maxrisk" value=""><br/>
          </td>
          <% else %>
          <td>
            <input class="form-control" type="number" id="<%= k %>_odd" value="<%= @bet_type['bet_type'][k]['odd'] %>"><br/>
          </td>
          <td>
            <input class="form-control" type="number" id="<%= k %>_maxrisk" value="<%= @bet_type['bet_type'][k]['maxrisk'] %>"><br/>
          </td>
          <% end %>
        </tr>
        <% end %>

      </tbody>
    </table>
  </div>

  <div id="bet_list_b21">
    <h5 class="box-title">ตารางราคา</h5>
    <table class="table table-responsive">
      <thead>
        <tr class="bg-primary text-inverse">
          <th width="10%">ประเภท</th>
          <th>รายการ</th>
          <th>Level 1</th>
          <th>Level 2</th>
          <th>Level 3</th>
          <th>Level 4</th>

        </tr>
      </thead>
      <tbody>
        <% @bet_type_list.each do |k, v| %>
        <tr>
          <td>
            <%=v%>
          </td>
          <td>
            <input class="form-control" type="text" value="ยอดแทงต่ำสุด" disabled=""><br/>
            <input class="form-control" type="text" value="ยอดแทงสูงสุด" disabled=""><br/>
            <input class="form-control" type="text" value="ส่วนลด (%)" disabled=""><br/>
          </td>
          <% if @bet_type['id'] == "new" %>
          <td>
            <input class="form-control" type="number" id="<%= k %>_minbet_level1" value=""><br/>
            <input class="form-control" type="number" id="<%= k %>_maxbet_level1" value=""><br/>
            <input class="form-control" type="number" id="<%= k %>_discount_level1" value=""><br/>
          </td>
          <td>
            <input class="form-control" type="number" id="<%= k %>_minbet_level2" value=""><br/>
            <input class="form-control" type="number" id="<%= k %>_maxbet_level2" value=""><br/>
            <input class="form-control" type="number" id="<%= k %>_discount_level2" value=""><br/>
          </td>
          <td>
            <input class="form-control" type="number" id="<%= k %>_minbet_level3" value=""><br/>
            <input class="form-control" type="number" id="<%= k %>_maxbet_level3" value=""><br/>
            <input class="form-control" type="number" id="<%= k %>_discount_level3" value=""><br/>
          </td>
          <td>
            <input class="form-control" type="number" id="<%= k %>_minbet_level4" value=""><br/>
            <input class="form-control" type="number" id="<%= k %>_maxbet_level4" value=""><br/>
            <input class="form-control" type="number" id="<%= k %>_discount_level4" value=""><br/>
          </td>
          <% else %>
          <td>
            <input class="form-control" type="number" id="<%= k %>_minbet_level1" value="<%= @bet_type['bet_type'][k]['level']['level1']['minbet'] %>"><br/>
            <input class="form-control" type="number" id="<%= k %>_maxbet_level1" value="<%= @bet_type['bet_type'][k]['level']['level1']['maxbet'] %>"><br/>
            <input class="form-control" type="number" id="<%= k %>_discount_level1" value="<%= @bet_type['bet_type'][k]['level']['level1']['discount'] %>"><br/>
          </td>
          <td>
            <input class="form-control" type="number" id="<%= k %>_minbet_level2" value="<%= @bet_type['bet_type'][k]['level']['level2']['minbet'] %>"><br/>
            <input class="form-control" type="number" id="<%= k %>_maxbet_level2" value="<%= @bet_type['bet_type'][k]['level']['level2']['maxbet'] %>"><br/>
            <input class="form-control" type="number" id="<%= k %>_discount_level2" value="<%= @bet_type['bet_type'][k]['level']['level2']['discount'] %>"><br/>
          </td>
          <td>
            <input class="form-control" type="number" id="<%= k %>_minbet_level3" value="<%= @bet_type['bet_type'][k]['level']['level3']['minbet'] %>"><br/>
            <input class="form-control" type="number" id="<%= k %>_maxbet_level3" value="<%= @bet_type['bet_type'][k]['level']['level3']['maxbet'] %>"><br/>
            <input class="form-control" type="number" id="<%= k %>_discount_level3" value="<%= @bet_type['bet_type'][k]['level']['level3']['discount'] %>"><br/>
          </td>
          <td>
            <input class="form-control" type="number" id="<%= k %>_minbet_level4" value="<%= @bet_type['bet_type'][k]['level']['level4']['minbet'] %>"><br/>
            <input class="form-control" type="number" id="<%= k %>_maxbet_level4" value="<%= @bet_type['bet_type'][k]['level']['level4']['maxbet'] %>"><br/>
            <input class="form-control" type="number" id="<%= k %>_discount_level4" value="<%= @bet_type['bet_type'][k]['level']['level4']['discount'] %>"><br/>
          </td>

          <% end %>
        </tr>
        <% end %>

      </tbody>
    </table>
  </div>

  <div class="checkbox checkbox-primary">
    <label class="">
      <input type="checkbox" id="accept-confirm">
      <span class="label-text">
        <small>ฉันตรวจสอบรายการครบถ้วนแล้ว</small>
      </span>
    </label>
  </div>

</form>

<button id="submit" class="btn btn-block btn-rounded btn-color-scheme">ยืนยันข้อมูล</button>

app/views/bet_types/edit.html.erb
<main class="main-wrapper clearfix">

      <!-- Page Title Area -->
      <div class="row page-title clearfix">
        <div class="page-title-left">
          <h5 class="mr-0 mr-r-5">ตารางการจ่าย</h5>

        </div>
        <!-- /.page-title-left -->
        <div class="page-title-right d-inline-flex">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="<%= root_path %>">หน้าหลัก</a>
            </li>
            <li class="breadcrumb-item">
              <a href="<%= admin_index_path %>">แอดมิน</a>
            </li>
            <li class="breadcrumb-item">
              <a href="<%= bet_types_path %>">ตารางการจ่าย</a>
            </li>
            <li class="breadcrumb-item active">แก้ไข</li>
          </ol>
        </div>
        <!-- /.page-title-right -->
      </div>
      <!-- /.page-title -->

  <div class="widget-list">
    <div class="row mr-b-0">
      <div class="col-md-2"></div>
      <div class="col-md-8">
        <div class="widget-bg">
          <div class="widget-body clearfix">

            <%= render 'form', bet_type: @bet_type %>

          </div>
        </div>
      </div>
    </div>
  </div>
</main>


<script src="<%= root_url%>assets/js/bet_types.js"></script>

app/views/bet_types/index.html.erb
<main class="main-wrapper clearfix">


    <!-- Page Title Area -->
    <div class="row page-title clearfix">
      <div class="page-title-left">
        <h5 class="mr-0 mr-r-5">ตารางการจ่าย</h5>

      </div>
      <!-- /.page-title-left -->
      <div class="page-title-right d-inline-flex">
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="<%= root_path %>">หน้าหลัก</a>
          </li>
          <li class="breadcrumb-item">
            <a href="<%= admin_index_path %>">แอดมิน</a>
          </li>
          <li class="breadcrumb-item active">
            ตารางการจ่าย
          </li>
        </ol>
      </div>
      <!-- /.page-title-right -->
    </div>
    <!-- /.page-title -->

  <div class="widget-list">
    <div class="row">

      <div class="col-md-3 widget-holder"></div>
      <div class="col-md-6  widget-holder">
        <div class="widget-bg">

          <table>
            <thead>
              <tr>
                <th width="10%">ประเภทหวย</th>
                <th width="30%"></th>
              </tr>
            </thead>

            <tbody>
              <% @bet_types.each do |bet_type| %>
                <tr>
                  <td><%= bet_type.product %></td>
                  <td>
                    <%= link_to 'Edit', edit_bet_type_path(bet_type) %>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/bet_types/new.html.erb
<main class="main-wrapper clearfix">
    <!-- Page Title Area -->
    <div class="row page-title clearfix">
      <div class="page-title-left">
        <h5 class="mr-0 mr-r-5">ตารางการจ่าย</h5>

      </div>
      <!-- /.page-title-left -->
      <div class="page-title-right d-inline-flex">
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="<%= root_path %>">หน้าหลัก</a>
          </li>
          <li class="breadcrumb-item">
            <a href="<%= admin_index_path %>">แอดมิน</a>
          </li>
          <li class="breadcrumb-item">
            <a href="<%= bet_types_path %>">ตารางการจ่าย</a>
          </li>
          <li class="breadcrumb-item active">เพิ่ม</li>
        </ol>
      </div>
      <!-- /.page-title-right -->
    </div>
    <!-- /.page-title -->

  <div class="widget-list">
    <div class="row mr-b-0">
      <div class="col-md-2"></div>
      <div class="col-md-8">
        <div class="widget-bg">
          <div class="widget-body clearfix">

            <%= render 'form', bet_type: @bet_type %>

          </div>
        </div>
      </div>
    </div>
  </div>
</main>


<script src="<%= root_url%>assets/js/bet_types.js"></script>

app/views/bet_types/show.html.erb
<main class="main-wrapper clearfix">

  <div class="widget-list">
    <div class="row">

      <div class="col-md-3 widget-holder"></div>
      <div class="col-md-6  widget-holder">
        <div class="widget-bg">

          <%= render 'form', bet_type: @bet_type %>

          <%= link_to 'Show', @bet_type %> |
          <%= link_to 'Back', bet_types_path %>
        </div>
      </div>
    </div>
  </div>
</main>