config/routes.rb
Rails.application.routes.draw do


  get 'pages/result'

  get 'products/laos'
  get 'products/thai'


  resources :bet_types
  get 'admin/index'
  get 'admin/rounds'
  get 'admin/requests'
  get 'admin/transactions'
  get 'admin/users'
  get 'admin/stats'
  get 'admin/notification'
  get 'admin/bypass'
  get 'admin/resetpwd'

  resources :transactions
  resources :rounds

  post 'rounds/calculate'
  post 'rounds/process1688'

  resources :requests do
    get 'confirm(.:format)' => 'requests#confirm'
    get 'cancel(.:format)' => 'requests#cancel'
  end
  get 'pages/index'
  get 'pages/faq'
  get 'pages/odd_table'
  root 'products#index'
  get 'products/thai'
  get 'products/laos'
  get 'products/index'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '*path' => redirect('/')
end

app/views/admin/_requests_all.html.erb
<table id="transactions_all" class="table table-sm table-striped table-responsive" data-toggle="datatables">
  <thead>
    <tr>
      <th>ลำดับ</th>
      <th>วันที่</th>
      <th>สมาชิก</th>
      <th>ชื่อบัญชี</th>
      <th>ประเภท</th>
      <th>จำนวนเงิน</th>
      <th>ยอดเงินคงเหลือ</th>
      <th>ธนาคารที่โอน</th>
      <th>เวลาที่โอน</th>
      <th>ชื่อบัญชี</th>
      <th>ธนาคาร</th>
      <th>เลขที่บัญชี</th>
      <th>สถานะ</th>
      <th>ไอดี</th>
    </tr>
  </thead>
  <tbody>

    <% @requests.each_with_index do |r, index| %>

    <tr>
      <td><%= index+1 %></td>
      <td><span id="request_<%= index %>_created_at"></span></td>
      <td><%= r['username'] %></td>
      <td><%= r['name'] %></td>
      <td><%= r['type'] %></td>
      <td><%= number_with_precision(r['value'], precision: 2, delimiter: ',') %></td>
      <td><%= number_with_precision(r['money720808'], precision: 2, delimiter: ',') %></td>
      <td><%= r['deposit_to_bank_id'] %></td>
      <td><%= r['deposit_timestamp'] %></td>
      <td><%= r['name'] %></td>
      <td><%= r['bank_id'] %></td>
      <td><%= r['bank_name'] %></td>
      <td><%= r['status'] %></td>
      <td><%= r['_id'].to_str.last(6) %></td>
    </tr>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <th>ลำดับ</th>
      <th>วันที่</th>
      <th>สมาชิก</th>
      <th>ชื่อบัญชี</th>
      <th>ประเภท</th>
      <th>จำนวนเงิน</th>
      <th>ยอดเงินคงเหลือ</th>
      <th>ธนาคารที่โอน</th>
      <th>เวลาที่โอน</th>
      <th>ชื่อบัญชี</th>
      <th>ธนาคาร</th>
      <th>เลขที่บัญชี</th>
      <th>สถานะ</th>
      <th>ไอดี</th>
    </tr>
  </tfoot>
</table>

app/views/admin/_requests_deposit.html.erb
<table id="transactions_deposit" class="table-sm table-striped table-responsive" data-toggle="datatables">
  <thead>
    <tr>
      <th>ลำดับ</th>
      <th width="15%">วันที่</th>
      <th>สมาชิก</th>
      <th>ชื่อบัญชี</th>
      <th>ประเภท</th>
      <th>จำนวนเงิน</th>
      <th>ยอดเงินคงเหลือ</th>
      <th>ธนาคารที่โอนเงินเข้า</th>
      <th>เวลาที่โอน</th>
      <th>หมายเหตุ</th>
      <th>สถานะ</th>
      <th>ไอดี</th>
      <th></th>
    </tr>
  </thead>
  <tbody>

    <% @deposit.each_with_index do |r, index| %>

    <tr>
      <td><%= index+1 %></td>
      <td><span id="deposit_<%= index %>_created_at"></span></td>
      <td><%= r['username'] %></td>
      <td><%= r['name'] %></td>
      <td><%= r['type'] %></td>
      <td><%= number_with_precision(r['value'], precision: 2, delimiter: ',') %></td>
      <td><%= number_with_precision(r['money720808'], precision: 2, delimiter: ',') %></td>
      <td><%= r['deposit_to_bank_id'] %></td>
      <td><%= r['deposit_timestamp'] %></td>
      <td><%= r['note'] %></td>
      <td><%= r['status'] %></td>
      <td><%= r['_id'].to_str.last(6) %></td>
      <td>
        <div class="dropdown">
          <a class="color-content-color" href="javascript:void(0);" data-toggle="dropdown" aria-expanded="false">
            <i class="material-icons list-icon">more_vert</i>
          </a>
          <div class="dropdown-menu" x-placement="bottom-start" style="position: absolute; transform: translate3d(0px, 19px, 0px); top: 0px; left: 0px; will-change: transform;">
            <a class="dropdown-item" rel="nofollow" href="<%= requests_path + "/" + r['_id'] + "/confirm"%>">
              <i class="material-icons list-icon float-left mr-r-10">done</i>
              ยืนยัน
            </a>
            <a class="dropdown-item" rel="nofollow" href="<%= requests_path + "/" + r['_id'] + "/edit"%>">
              <i class="material-icons list-icon float-left mr-r-10">mode_edit</i>
              แก้ไข
            </a>
            <a class="dropdown-item" rel="nofollow" href="<%= requests_path + "/" + r['_id'] + "/cancel"%>">
              <i class="material-icons list-icon float-left mr-r-10">clear</i>
              ยกเลิก
            </a>
          </div>
        </div>
      </td>
    </tr>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <th>ลำดับ</th>
      <th>วันที่</th>
      <th>สมาชิก</th>
      <th>ชื่อบัญชี</th>
      <th>ประเภท</th>
      <th>จำนวนเงิน</th>
      <th>ยอดเงินคงเหลือ</th>
      <th>ธนาคารที่โอนเงินเข้า</th>
      <th>เวลาที่โอน</th>
      <th>หมายเหตุ</th>
      <th>สถานะ</th>
      <th>ไอดี</th>
      <th></th>
    </tr>
  </tfoot>
</table>

app/views/admin/_requests_summary.html.erb
<table id="transactions_summary" class="table table-sm table-striped table-responsive table-hover">
  <thead>
    <tr>
      <th>ลำดับ</th>
      <th>วันที่</th>
      <th>ยอดแจ้งฝาก</th>
      <th>ยอดฝากที่ได้รับยืนยัน</th>
      <th>ยอดแจ้งถอน</th>
      <th>ยอดถอนที่ได้รับยืนยัน</th>
      <th>ยอดฝาก-ยอดถอน</th>
    </tr>
  </thead>
  <tbody id="transactions_summary_tbody">


  </tbody>
</table>


<div id="filter_bydate_div">

  <div class="modal modal-color-scheme fade bs-modal-lg-color-scheme modal-fullscreen" id="transactionSummary" role="dialog" aria-labelledby="transactionSummary" aria-hidden="true" style="display: none">
    <div class="modal-dialog modal-lg bs-modal-lg-color-scheme">
      <div class="modal-content">
        <div class="modal-header text-inverse">
          <button type="button" class="close"  data-dismiss="modal" aria-hidden="true">×</button>
          <h5 class="modal-title" id="myLargeModalLabel">รายการแทงย้อนหลังรายงวด</h5>
        </div>
        <div class="modal-body">


          <div id="RequestSummaryContent"></div>
        </div>
        <div class="modal-footer">

          <button type="button" class="btn btn-danger btn-rounded ripple text-left" data-dismiss="modal">ปิดหน้าต่าง</button>

        </div>
      </div>
      <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
  </div>
  <!-- /.modal -->
</div>

app/views/admin/_requests_withdraw.html.erb
<table id="transactions_withdraw" class="table-sm table-striped table-responsive" data-toggle="datatables">
  <thead>
    <tr>
      <th>ลำดับ</th>
      <th>วันที่</th>
      <th>สมาชิก</th>
      <th>ชื่อบัญชี</th>
      <th>ประเภท</th>
      <th>จำนวนเงิน</th>
      <th>ชื่อบัญชี</th>
      <th>ธนาคาร</th>
      <th>เลขที่บัญชี</th>
      <th>สถานะ</th>
      <th>ไอดี</th>
      <th></th>
    </tr>
  </thead>
  <tbody>

    <% @withdraw.each_with_index do |r, index| %>

    <tr>
      <td><%= index+1 %></td>
      <td><span id="withdraw_<%= index %>_created_at"></span></td>
      <td><%= r['username'] %></td>
      <td><%= r['name'] %></td>
      <td><%= r['type'] %></td>
      <td><%= number_with_precision(r['value'], precision: 2, delimiter: ',') %></td>
      <td><%= r['name'] %></td>
      <td><%= r['bank_id'] %></td>
      <td><%= r['bank_name'] %></td>
      <td><%= r['status'] %></td>
      <td><%= r['_id'].to_str.last(6) %></td>
      <td>
        <div class="dropdown">
          <a class="color-content-color" href="javascript:void(0);" data-toggle="dropdown" aria-expanded="false">
            <i class="material-icons list-icon">more_vert</i>
          </a>
          <div class="dropdown-menu" x-placement="bottom-start" style="position: absolute; transform: translate3d(0px, 19px, 0px); top: 0px; left: 0px; will-change: transform;">
            <a class="dropdown-item" rel="nofollow" href="<%= requests_path + "/" + r['_id'] + "/confirm"%>">
              <i class="material-icons list-icon float-left mr-r-10">done</i>
              ยืนยัน
            </a>
            <a class="dropdown-item" href="javascript:void(0);">
              <i class="material-icons list-icon float-left mr-r-10">mode_edit</i>
              แก้ไข
            </a>
            <a class="dropdown-item" rel="nofollow" href="<%= requests_path + "/" + r['_id'] + "/cancel"%>">
              <i class="material-icons list-icon float-left mr-r-10">clear</i>
              ยกเลิก
            </a>
          </div>
        </div>
      </td>
    </tr>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <th>ลำดับ</th>
      <th>วันที่</th>
      <th>สมาชิก</th>
      <th>ชื่อบัญชี</th>
      <th>ประเภท</th>
      <th>จำนวนเงิน</th>
      <th>ชื่อบัญชี</th>
      <th>ธนาคาร</th>
      <th>เลขที่บัญชี</th>
      <th>สถานะ</th>
      <th>ไอดี</th>
      <th></th>
    </tr>
  </tfoot>
</table>

app/views/admin/_rounds_laos.html.erb
<%= form_with(model: rounds, local: true, class: "form") do |form| %>

<div class="input-group input-has-value">
    <label class="col-md-3 col-form-label" for="l10">งวดวันที่ :</label>
  <input type="text" class="form-control datepicker" placeholder="งวดวันที่">
  <span class="input-group-addon">
    <i class="list-icon material-icons">date_range</i>
  </span>
</div>

<div class="form-group mr-b-40 input-has-value">

    <label class="col-md-3 col-form-label" for="l10">วันเวลาที่เปิดรับแทง :</label>
  <input
    class="form-control daterange"
    placeholder="กรุณาเลือกวันเวลาที่เปิดรับแทง"
    data-plugin-options="{&quot;timePicker&quot;: true, &quot;opens&quot;: &quot;right&quot;, &quot;timePicker24Hour&quot;: true, &quot;timePickerIncrement&quot;: 15, &quot;locale&quot;: { &quot;format&quot;: &quot;DD/MM/YYYY h:mm A&quot; }}">
</div>

<div class="form-group row">
  <label class="col-md-3 col-form-label" for="l10">ความเสี่ยงสูงสุด :</label>
  <div class="col-md-9">
    <div class="input-group">
        <%= form.number_field "rounds", id: :value, autofocus: true, placeholder: "ความเสี่ยงสูงสุด", class:"form-control", step: :any %>
    </div>
  </div>
</div>


<div class="form-group row">
  <label class="col-md-3 col-form-label" for="l10"> สามตัวบน:</label>
  <div class="col-md-3">
    <div class="input-group">
        <%= form.number_field "สามตัวบน", id: :value, autofocus: true, placeholder: "750", class:"form-control", step: :any %>
    </div>
  </div>
  <div class="col-md-3">
    <div class="input-group">
        <%= form.number_field "เลขที่ออก", id: :value, autofocus: true, placeholder: "750", class:"form-control", step: :any %>
    </div>
  </div>
</div>

<div class="form-group row">
  <label class="col-md-3 col-form-label" for="l10"> สามตัวโต๊ด:</label>
  <div class="col-md-9">
    <div class="input-group">
        <%= form.number_field "สามตัวโต๊ด", id: :value, autofocus: true, placeholder: "120", class:"form-control", step: :any %>
    </div>
  </div>
</div>

<div class="form-group row">
  <label class="col-md-3 col-form-label" for="l10"> สามตัวล่าง:</label>
  <div class="col-md-9">
    <div class="input-group">
        <%= form.number_field "สามตัวล่าง", id: :value, autofocus: true, placeholder: "120", class:"form-control", step: :any %>
    </div>
  </div>
</div>

<div class="form-group row">
  <label class="col-md-3 col-form-label" for="l10"> สามตัวหน้า:</label>
  <div class="col-md-9">
    <div class="input-group">
        <%= form.number_field "สามตัวล่าง", id: :value, autofocus: true, placeholder: "120", class:"form-control", step: :any %>
    </div>
  </div>
</div>

<div class="form-group row">
  <label class="col-md-3 col-form-label" for="l10"> สองตัวบน:</label>
  <div class="col-md-9">
    <div class="input-group">
        <%= form.number_field "สองตัวบน", id: :value, autofocus: true, placeholder: "120", class:"form-control", step: :any %>
    </div>
  </div>
</div>

<div class="form-group row">
  <label class="col-md-3 col-form-label" for="l10"> สองตัวล่าง:</label>
  <div class="col-md-9">
    <div class="input-group">
        <%= form.number_field "สองตัวล่าง", id: :value, autofocus: true, placeholder: "120", class:"form-control", step: :any %>
    </div>
  </div>
</div>

<div class="form-group row">
  <label class="col-md-3 col-form-label" for="l10"> วิ่งบน:</label>
  <div class="col-md-9">
    <div class="input-group">
        <%= form.number_field "วิ่งบน", id: :value, autofocus: true, placeholder: "120", class:"form-control", step: :any %>
    </div>
  </div>
</div>

<div class="form-group row">
  <label class="col-md-3 col-form-label" for="l10"> วิ่งล่าง:</label>
  <div class="col-md-9">
    <div class="input-group">
        <%= form.number_field "วิ่งล่าง", id: :value, autofocus: true, placeholder: "120", class:"form-control", step: :any %>
    </div>
  </div>
</div>


<h3>เลขอั้น</h3>

<div class="form-group row">
  <div class="col-md-3">
    <div class="input-group">
        <%= form.number_field "เลข", id: :value, autofocus: true, placeholder: "990", class:"form-control", step: :any %>
    </div>
  </div>
  <div class="col-md-3">
    <div class="input-group">
        <%= form.number_field "เลข", id: :value, autofocus: true, placeholder: "150", class:"form-control", step: :any %>
    </div>
  </div>
  <div class="col-md-3">
    <div class="input-group">
        <%= form.number_field "เลข", id: :value, autofocus: true, placeholder: "200,000", class:"form-control", step: :any %>
    </div>
  </div>
</div>



<% end %>

app/views/admin/_users_all.html.erb
<table id="users_all" class="table table-sm table-striped table-responsive" data-toggle="datatables">
  <thead>
    <tr>
      <th>ลำดับ</th>
      <th>สมาชิก</th>
      <th>ชื่อบัญชี</th>
      <th>ยอดเงินคงเหลือ</th>
      <th>ยอดฝาก</th>
      <th>ยอดถอน</th>
      <th>ยอดแทงทั้งหมด</th>
      <th>ยอดได้ทั้งหมด</th>
      <th>วันที่สมัครสมาชิก</th>
      <th>วันที่เข้าระบบล่าสุด</th>
      <th>IP Address</th>
      <th>bypass</th>
      <th>reset password</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each_with_index do |u, index| %>
    <% if u['username'] != '168899' %>

    <tr>
      <td><%= index+1 %></td>
      <td><%= u['username'] %></td>
      <td><%= u['name'] %></td>
      <td><%= number_with_precision(u['money720808'], precision: 2, delimiter: ',') %></td>
      <td><%= number_with_precision(Request.where(username: u._id, type: 'ฝาก', status: 'สำเร็จ').sum(:value), precision: 2, delimiter: ',') %></td>
      <td><%= number_with_precision(Request.where(username: u._id, type: 'ถอน').sum(:value), precision: 2, delimiter: ',') %></td>
      <td><%= number_with_precision(Transaction.where(username: u._id).sum(:bet_value), precision: 2, delimiter: ',') %></td>
      <td><%= number_with_precision(Transaction.where(username: u._id, status: 'ถูก').sum(:paid), precision: 2, delimiter: ',') %></td>
      <td><%= u['created_at'] %></td>
      <td><%= u['current_sign_in_at'] %></td>
      <td><%= u['current_sign_in_ip'] %></td>
      <td><a href="<%= admin_bypass_path %>/?u=<%= u['_id'] %>">bypass</a></td>
      <td><a href="#" onclick="resetpwd('<%= u['_id'] %>');">reset password</a></td>

    </tr>

    <% end %>

    <% end %>

  </tbody>
  <tfoot>
    <tr>
      <th>ลำดับ</th>
      <th>สมาชิก</th>
      <th>ชื่อบัญชี</th>
      <th>ยอดเงินคงเหลือ</th>
      <th>ยอดฝาก</th>
      <th>ยอดถอน</th>
      <th>ยอดแทงทั้งหมด</th>
      <th>ยอดได้ทั้งหมด</th>
      <th>วันที่สมัครสมาชิก</th>
      <th>วันที่เข้าระบบล่าสุด</th>
      <th>IP Address</th>
      <th>bypass</th>
      <th>reset password</th>
    </tr>
  </tfoot>
</table>

app/views/admin/index.html.erb
<h1>Admin#index</h1>
<p>Find me in app/views/admin/index.html.erb</p>

app/views/admin/requests.html.erb
<script>
  var requests = "<%= @requests.to_json.gsub("money720808", "money") %>";
  requests = JSON.parse(requests.replace(/&quot;/g, '\"'));
  var deposit = "<%= @deposit.to_json.gsub("money720808", "money") %>";
  deposit = JSON.parse(deposit.replace(/&quot;/g, '\"'));
  var withdraw = "<%= @withdraw.to_json.gsub("money720808", "money") %>";
  withdraw = JSON.parse(withdraw.replace(/&quot;/g, '\"'));
</script>

<main class="main-wrapper clearfix" id="main-request">
  <!-- Page Title Area -->
   <div class="row page-title clearfix">
       <div class="page-title-left">
           <h5 class="mr-0 mr-r-5">รายการฝากถอน</h5>

       </div>
       <!-- /.page-title-left -->
       <div class="page-title-right d-inline-flex">
           <ol class="breadcrumb">
               <li class="breadcrumb-item"><a href="<%= root_path %>">หน้าหลัก</a></li>
               <li class="breadcrumb-item"><a href="<%= admin_index_path %>">แอดมิน</a></li>
               <li class="breadcrumb-item active">ฝากถอน</li>
           </ol>
       </div>
       <!-- /.page-title-right -->
   </div>
   <!-- /.page-title -->

  <div class="widget-list">
    <div class="row">
      <div class="col-md-12  widget-holder">
        <div class="widget-bg">
          <div class="widget-body clearfix">
            <div class="tabs">
              <ul class="nav nav-tabs">
                <li class="nav-item">
                  <a class="nav-link active" href="#deposit" data-toggle="tab" aria-expanded="true">ฝากเงิน</a>
                </li>
                <li class="nav-item" aria-expanded="false">
                  <a class="nav-link" href="#withdraw" data-toggle="tab" aria-expanded="true">ถอนเงิน</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#status" data-toggle="tab" aria-expanded="true">รายการทั้งหมด</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#summary" data-toggle="tab" aria-expanded="true">สรุปยอดรายวัน</a>
                </li>
              </ul>
              <!-- /.nav-tabs -->
              <div class="tab-content">
                <div class="tab-pane active" id="deposit" aria-expanded="false">
                  <%= render 'requests_deposit', deposit: @deposit %>
                </div>
                <div class="tab-pane" id="withdraw" aria-expanded="false">
                  <%= render 'requests_withdraw', withdraw: @withdraw %>
                </div>
                <div class="tab-pane" id="status" aria-expanded="false">
                  <%= render 'requests_all', withdraw: @requests %>
                </div>
                <div class="tab-pane" id="summary" aria-expanded="false">
                  <%= render 'requests_summary'%>
                </div>
              </div>
              <!-- /.tab-content -->
            </div>
            <!-- /.tabs -->
          </div>
          <!-- /.widget-body -->
        </div>
        <!-- /.widget-bg -->
      </div>
    </div>
    <!-- /.row -->
  </div>

</main>


<script src="<%= root_url%>assets/js/admin/requests_168.js"></script>

app/views/admin/rounds.html.erb
<main class="main-wrapper clearfix">

  <div class="widget-list">
    <div class="row">
      <div class="col-md-12  widget-holder">
        <div class="widget-bg">
          <div class="widget-body clearfix">
            <div class="tabs">
              <ul class="nav nav-tabs nav-justified">
                <li class="nav-item">
                  <a class="nav-link active" href="#deposit" data-toggle="tab" aria-expanded="true">รอบที่กำลังเปิด</a>
                </li>
                <li class="nav-item" aria-expanded="false">
                  <a class="nav-link" href="#laos" data-toggle="tab" aria-expanded="true">หวยลาว</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#status" data-toggle="tab" aria-expanded="true">หวยไทย</a>
                </li>
              </ul>
              <!-- /.nav-tabs -->
              <div class="tab-content">
                <div class="tab-pane active" id="deposit" aria-expanded="false">
                  <p>เพื่อความรวดเร็ว และสะดวกต่อการตรวจสอบของเจ้าหน้าที่ กรุณาโอนเงินมาเป็นเศษสตางค์ เช่น 1000.35 บาท</p>
                </div>
                <div class="tab-pane" id="laos" aria-expanded="false">
                  <%= render 'rounds_laos', rounds: @rounds %>
                </div>
                <div class="tab-pane" id="status" aria-expanded="false">
                </div>
              </div>
              <!-- /.tab-content -->
            </div>
            <!-- /.tabs -->
          </div>
          <!-- /.widget-body -->
        </div>
        <!-- /.widget-bg -->
      </div>
    </div>
    <!-- /.row -->
  </div>

</main>

app/views/admin/stats.html.erb
<h1>Admin#stat</h1>
<p>Find me in app/views/admin/stat.html.erb</p>

app/views/admin/transactions.html.erb
<h1>Admin#transaction</h1>
<p>Find me in app/views/admin/transaction.html.erb</p>

app/views/admin/users.html.erb
<main class="main-wrapper clearfix">
  <!-- Page Title Area -->
   <div class="row page-title clearfix">
       <div class="page-title-left">
           <h5 class="mr-0 mr-r-5">ผู้ใช้งานทั้งหมด</h5>

       </div>
       <!-- /.page-title-left -->
       <div class="page-title-right d-inline-flex">
           <ol class="breadcrumb">
               <li class="breadcrumb-item"><a href="<%= root_path %>">หน้าหลัก</a></li>
               <li class="breadcrumb-item active">ผู้ใช้งานทั้งหมด</li>
           </ol>
       </div>
       <!-- /.page-title-right -->
   </div>
   <!-- /.page-title -->

  <div class="widget-list">
    <div class="row">
      <div class="col-md-12  widget-holder">
        <div class="widget-bg">
          <div class="widget-body clearfix">
            <%= render 'users_all' %>
          </div>
          <!-- /.widget-body -->
        </div>
        <!-- /.widget-bg -->
      </div>
    </div>
    <!-- /.row -->
  </div>

</main>


<script src="<%= root_url%>assets/js/admin/users_1688.js"></script>