config/routes.rb
Rails.application.routes.draw do


  get 'pages/result'

  get 'products/laos'
  get 'products/thai'


  resources :bet_types
  get 'admin/index'
  get 'admin/rounds'
  get 'admin/requests'
  get 'admin/transactions'
  get 'admin/users'
  get 'admin/stats'
  get 'admin/notification'
  get 'admin/bypass'
  get 'admin/resetpwd'

  resources :transactions
  resources :rounds

  post 'rounds/calculate'
  post 'rounds/process1688'

  resources :requests do
    get 'confirm(.:format)' => 'requests#confirm'
    get 'cancel(.:format)' => 'requests#cancel'
  end
  get 'pages/index'
  get 'pages/faq'
  get 'pages/odd_table'
  root 'products#index'
  get 'products/thai'
  get 'products/laos'
  get 'products/index'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '*path' => redirect('/')
end

app/models/round.rb
class Round
  include Mongoid::Document
  include Mongoid::Timestamps::Created
  include Mongoid::Timestamps::Updated

  field :result_date,             type: String
  field :result_time,             type: String
  field :status,                  type: String, default: "open"
  field :product,                 type: String
  field :payout,                  type: Object
  field :limit,                   type: Object
  field :result_number,           type: Object
  field :result_number_bet_type,  type: Object

end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController
  before_action :set_round, only: %i[show edit update destroy]
  before_action :authenticate_admin

  # GET /rounds
  # GET /rounds.json
  def index
    @rounds = Round.all
    @bet_type = BetType.all
  end

  # GET /rounds/1
  # GET /rounds/1.json
  def show
    @bet_type = BetType.where(product: @round['product']).first
    @transactions = Transaction.where(round: params[:id])

    @bet_type_list = { 'b31' => '3ตัวบน',
                       'b32' => '3ตัวโต๊ด',
                       'b33' => '3ตัวล่าง',
                       'b34' => '3ตัวหน้า',
                       'b21' => '2ตัวบน',
                       'b22' => '2ตัวล่าง',
                       'b23' => '2ตัวโต๊ด',
                       'b11' => 'วิ่งบน',
                       'b12' => 'วิ่งล่าง' }

    @summary = Hash.new
    @summary['total'] = Hash.new
    @summary['total']['count'] = @transactions.count;
    @summary['total']['bet'] = @transactions.map { |h| h['bet_value'] }.sum
    @summary['total']['user'] = @transactions.map { |h| h['username'] }.uniq.count
    @summary['total']['discount'] = @transactions.map { |h| h['discount']*h['bet_value']/100 }.sum
    @summary['total']['paid'] = @transactions.map { |h| h['paid'] }.sum
    @summary['total']['pnl'] = @summary['total']['bet'] - @summary['total']['discount'] - @summary['total']['paid']

    @bet_type_list.each do |k, v|
      @summary[k] = Hash.new
      @summary[k]['count'] = @transactions.map { |h| h['bet_type'] == k ? 1 : 0 }.sum
      @summary[k]['bet'] = @transactions.map { |h| h['bet_type'] == k ? h['bet_value'] : 0 }.sum
      @summary[k]['user'] = @transactions.map { |h| h['bet_type'] == k ? h['username'] : nil }.uniq.count - 1
      @summary[k]['discount'] = @transactions.map { |h| h['bet_type'] == k ? h['discount']*h['bet_value']/100 : 0 }.sum
      @summary[k]['paid'] = @transactions.map { |h| h['bet_type'] == k ? h['paid'] : 0 }.sum
      @summary[k]['pnl'] = @summary[k]['bet'] - @summary[k]['discount'] - @summary[k]['paid']

    end
  end

  # GET /rounds/new
  def new
    @round = Round.new
    @bet_type_list = { 'b31' => '3ตัวบน',
                       'b32' => '3ตัวโต๊ด',
                       'b33' => '3ตัวล่าง',
                       'b34' => '3ตัวหน้า',
                       'b21' => '2ตัวบน',
                       'b22' => '2ตัวล่าง',
                       'b23' => '2ตัวโต๊ด',
                       'b11' => 'วิ่งบน',
                       'b12' => 'วิ่งล่าง' }
    @round['id'] = "new"
  end

  # GET /rounds/1/edit
  def edit
    @bet_type_list = { 'b31' => '3ตัวบน',
                       'b32' => '3ตัวโต๊ด',
                       'b33' => '3ตัวล่าง',
                       'b34' => '3ตัวหน้า',
                       'b21' => '2ตัวบน',
                       'b22' => '2ตัวล่าง',
                       'b23' => '2ตัวโต๊ด',
                       'b11' => 'วิ่งบน',
                       'b12' => 'วิ่งล่าง' }
    @idx = params[:id]
  end

  # POST /rounds/calculate
  def calculate
    @round = Round.find(round_params['round_id'])
    msg = []

    if @round['status'] == 'proceed'
      msg = "รอบหวยนี้ได้ประมวลผลรายการแทงแล้ว"
      render json: {"msg": msg}, status: :unprocessable_entity
      return
    end

    if @round['status'] == 'open'
      msg = "รอบหวยนี้ยังไม่ปิดรับแทง กรุณาปิดรับแทง"
      render json: {"msg": msg}, status: :unprocessable_entity
      return
    end

    # Generate Result for each bet type
    if @round['product'] == 'หวยไทย'
      @result_number = Hash.new
      @result_number['b31'] = [@round['result_number']['6digits'][3..5]]
      @result_number['b32'] = @round['result_number']['6digits'][3..5].chars.permutation.map &:join
      @result_number['b32'] = @result_number['b32'].uniq
      @result_number['b33'] = [ @round['result_number']['3digits_1'],
                                @round['result_number']['3digits_2'],
                                @round['result_number']['3digits_3'],
                                @round['result_number']['3digits_4'] ].reject { |c| c.empty? }
      @result_number['b34'] = [ @round['result_number']['3digits_5'],
                              @round['result_number']['3digits_6'], ].reject { |c| c.empty? }
      @result_number['b21'] = [ @round['result_number']['6digits'][4..5] ]
      @result_number['b22'] = [ @round['result_number']['2digits'] ]
      @result_number['b23'] = @round['result_number']['6digits'][3..5].chars.permutation(2).map &:join
      @result_number['b23'] = @result_number['b23'].uniq
      @result_number['b11'] = @round['result_number']['6digits'][3..5].chars.uniq
      @result_number['b12'] = @round['result_number']['2digits'].chars.uniq

      @round.update("result_number_bet_type" => @result_number)
      @round.update('status' => 'close')

      logger.debug "CalculateResult: #{@result_number.to_yaml}"
      msg.push( @result_number )

    elsif @round['product'] == 'หวยลาว'
      @result_number = Hash.new
      @result_number['b31'] = [@round['result_number']['3digits']]
      @result_number['b32'] = @round['result_number']['3digits'].chars.permutation.map &:join
      @result_number['b32'] = @result_number['b32'].uniq
      @result_number['b21'] = [@round['result_number']['2digits']]
      @result_number['b22'] = [@round['result_number']['4digits'][0..1]]

      @round.update("result_number_bet_type" => @result_number)
      @round.update('status' => 'close')

      logger.debug "CalculateResult: #{@result_number.to_yaml}"
      msg.push( @result_number )

    end


    render json: {"msg": msg.to_json}, status: :ok
  end

  # POST /rounds/process1688
  def process1688
    @round = Round.find(round_params['round_id'])

    if @round['status'] == 'proceed'
      msg = "รอบหวยนี้ได้ประมวลผลรายการแทงแล้ว"
      render json: {"msg": msg}, status: :unprocessable_entity
      return
    end

    if @round['status'] == 'open'
      msg = "รอบหวยนี้ยังไม่ปิดรับแทง กรุณาปิดรับแทง"
      render json: {"msg": msg}, status: :unprocessable_entity
      return
    end

    mBet = 0
    mPay = 0
    mDiscount = 0

    transactions = Transaction.where(status: "รอ", round: round_params['round_id'])
    @tc = transactions.count
    transactions.each do |t|
      @tr = t
      user = User.find(t['username'])

      isWin = 0
      @round['result_number_bet_type'][t['bet_type']].each do |r|
        if r == t['number']
          isWin = 1
          break;
        end
      end

      paid = 0
      mDiscount += (t['bet_value']*t['discount']/100)

      if isWin == 0
        #paid = (t['discount'] / 100)*t['bet_value']
        t.update("status" => "ผิด", "paid" => paid)
      else
        paid = (t['bet_value']*t['odd'])
        t.update("status" => "ถูก", "paid" => paid)
      end

      m = user.money720808 + paid
      mPay += paid
      user.update("money720808" => m)

      mBet += t['bet_value']
    end

    @round.update('status' => 'proceed')


    msg = "ยอดแทงทั้งหมด " + mBet.to_s + " บาท<br>ส่วนลดทั้งหมด " + mDiscount.to_s + " บาท<br>ยอดจ่าย " + mPay.to_s + " บาท<br>กำไร " + (mBet-mPay-mDiscount).to_s + " บาท"
    render json: {"msg": msg}, status: :ok
  end

  # POST /rounds
  # POST /rounds.json
  def create
    @round = Round.new(round_params)
    @res = Round.where(status: 'open', product: params[:_json][0][:product])

    logger.debug "@res: #{@res.count}"

    msg = ""
    if @res.count == 0 && @round.save
      msg = "เปิดรอบแทงสำเร็จ"
      render json: {"msg": msg}
    else
      msg = round_params['product'] + " ได้ถูกสร้างขึ้นมาแล้ว"
      render json: {"msg": msg}, status: :unprocessable_entity
    end

  end

  # PATCH/PUT /rounds/1
  # PATCH/PUT /rounds/1.json
  def update
    if @round['status'] == 'proceed'
      msg = "รอบหวยนี้ได้ประมวลผลรายการแทงแล้ว"
      render json: {"msg": msg}, status: :unprocessable_entity
      return
    end

    if @round.update(round_params)
      msg = "บันทึกข้อมูลสำเร็จ"
      render json: {"msg": msg}
    else
      msg = "เกิดข้อผิดพลาดในการบันทึกข้อมูล"
      render json: {"msg": msg}, status: :unprocessable_entity
    end
  end

  # DELETE /rounds/1
  # DELETE /rounds/1.json
  def destroy
    @round.destroy
    respond_to do |format|
      format.html { redirect_to rounds_url, notice: 'Round was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def authenticate_admin
    if !(user_signed_in? && current_user.username == '168899')
      redirect_to root_path
    end
  end


  # Use callbacks to share common setup or constraints between actions.
  def set_round
    @round = Round.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def round_params
    r_params = params[:_json][0]

    r_params = r_params.as_json

    r_params
  end
end

app/helpers/rounds_helper.rb
module RoundsHelper
end

app/views/rounds/edit.html.erb
<main class="main-wrapper clearfix">

  <!-- Page Title Area -->
  <div class="row page-title clearfix">
    <div class="page-title-left">
      <h5 class="mr-0 mr-r-5">แก้ไขรอบหวย</h5>

    </div>
    <!-- /.page-title-left -->
    <div class="page-title-right d-inline-flex">
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="<%= root_path %>">หน้าหลัก</a>
        </li>
        <li class="breadcrumb-item">
          <a href="<%= admin_index_path %>">แอดมิน</a>
        </li>
        <li class="breadcrumb-item">
          <a href="<%= rounds_path %>">รอบหวย</a>
        </li>
        <li class="breadcrumb-item active">แก้ไข</li>
      </ol>
    </div>
    <!-- /.page-title-right -->
  </div>
  <!-- /.page-title -->

  <div class="widget-list">
    <div class="row mr-b-0">
      <div class="col-md-2"></div>
      <div class="col-md-8">
        <div class="widget-bg">
          <div class="widget-body clearfix">

            <%= render 'form', round: @round, bet_type: @bet_type %>

          </div>
        </div>
      </div>
    </div>
  </div>
</main>

<script src="<%= root_url%>assets/js/admin/round_168.js"></script>

app/views/rounds/index.html.erb
<main class="main-wrapper clearfix">

  <!-- Page Title Area -->
  <div class="row page-title clearfix">
    <div class="page-title-left">
      <h5 class="mr-0 mr-r-5">รอบหวย</h5>

    </div>
    <!-- /.page-title-left -->
    <div class="page-title-right d-inline-flex">
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="<%= root_path %>">หน้าหลัก</a>
        </li>
        <li class="breadcrumb-item">
          <a href="<%= admin_index_path %>">แอดมิน</a>
        </li>
        <li class="breadcrumb-item active">รอบหวย</li>
      </ol>
    </div>
    <!-- /.page-title-right -->
  </div>
  <!-- /.page-title -->

  <div class="widget-list">
    <div class="row mr-b-0">
      <div class="col-md-12">
        <div class="widget-bg">
          <div class="widget-body clearfix">
            <table id="round_all" class="table-sm table-striped table-responsive" data-toggle="datatables">
              <thead>
                <tr>
                  <th>สร้างวันที่</th>
                  <th>ประเภทหวย</th>
                  <th>งวดวันที่</th>
                  <th>เวลาหยุดรับแทง</th>
                  <th>สถานะ</th>
                  <th></th>
                </tr>
              </thead>

              <tbody>
                <% @rounds.each do |round| %>
                <tr>
                  <td><%= round['created_at'] %></td>
                  <td><%= round['product'] %></td>
                  <td><%= round['result_date'] %></td>
                  <td><%= round['result_time'] %></td>
                  <td><%= round['status'] == 'open' ? 'เปิดรับแทง' : (round['status'] == 'close' ? 'ปิดรับแทง' : 'ออกผลรางวัลแล้ว') %></td>
                  <td><%= link_to 'สรุป', round_path(round) %> | <%= link_to 'แก้ไข', edit_round_path(round) %></td>
                </tr>
                <% end %>
              </tbody>
            </table>

          </div>
        </div>
      </div>
    </div>
  </div>
</main>

<script src="<%= root_url%>assets/js/admin/rounds_index.js"></script>

app/views/rounds/new.html.erb
<main class="main-wrapper clearfix">

  <!-- Page Title Area -->
  <div class="row page-title clearfix">
    <div class="page-title-left">
      <h5 class="mr-0 mr-r-5">เพิ่มรอบ</h5>

    </div>
    <!-- /.page-title-left -->
    <div class="page-title-right d-inline-flex">
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="<%= root_path %>">หน้าหลัก</a>
        </li>
        <li class="breadcrumb-item">
          <a href="<%= admin_index_path %>">แอดมิน</a>
        </li>
        <li class="breadcrumb-item">
          <a href="<%= rounds_path %>">รอบหวย</a>
        </li>
        <li class="breadcrumb-item active">เพิ่ม</li>
      </ol>
    </div>
    <!-- /.page-title-right -->
  </div>
  <!-- /.page-title -->

  <div class="widget-list">
    <div class="row mr-b-0">
      <div class="col-md-2"></div>
      <div class="col-md-8">
        <div class="widget-bg">
          <div class="widget-body clearfix">

            <%= render 'form', round: @round, bet_type: @bet_type %>

          </div>
        </div>
      </div>
    </div>
  </div>
</main>

<script src="<%= root_url%>assets/js/admin/round_168.js"></script>

app/views/rounds/show.html.erb
<script>
  var transactions = "<%= @transactions.to_json.gsub("money720808", "money") %>";
  transactions = JSON.parse(transactions.replace(/&quot;/g, '\"'));
</script>

<main class="main-wrapper clearfix">
  <!-- Page Title Area -->
   <div class="row page-title clearfix">
       <div class="page-title-left">
           <h5 class="mr-0 mr-r-5">เติมเงิน</h5>

       </div>
       <!-- /.page-title-left -->
       <div class="page-title-right d-inline-flex">
           <ol class="breadcrumb">

               <li class="breadcrumb-item">
                 <a href="<%= root_path %>">หน้าหลัก</a>
               </li>
               <li class="breadcrumb-item">
                 <a href="<%= admin_index_path %>">แอดมิน</a>
               </li>
               <li class="breadcrumb-item">
                 <a href="<%= rounds_path %>">รอบหวย</a>
               </li>

               <li class="breadcrumb-item active">สรุป</li>
           </ol>
       </div>
       <!-- /.page-title-right -->
   </div>
   <!-- /.page-title -->

  <div class="widget-list">
    <div class="row mr-b-0">
      <div class="col-md-12">
        <div class="widget-bg">
          <div class="widget-body clearfix">

            <div class="tabs">
              <ul class="nav nav-tabs nav-justified">
                <li class="nav-item">
                  <a class="nav-link active" href="#all" data-toggle="tab" aria-expanded="true">รายการแทงทั้งหมด</a>
                </li>
                <li class="nav-item" aria-expanded="false">
                  <a class="nav-link" href="#3digits" data-toggle="tab" aria-expanded="true">3 ตัว</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#2digits" data-toggle="tab" aria-expanded="true">2 ตัว</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#1digits" data-toggle="tab" aria-expanded="true">1 ตัว</a>
                </li>
              </ul>
              <!-- /.nav-tabs -->
              <div class="tab-content">
                <h3><%=@round.product%> - <%=@round.result_date%> (<%=@round.status%>)</h3>
                <div class="tab-pane active" id="all" aria-expanded="false">
                  <hr />
                  <h5>ตารางสรุป</h5>
                  <table id="transaction_summary" class="table table-sm table-striped table-responsive">
                    <thead>
                      <tr>
                        <th>ประเภท</th>
                        <th>จำนวนรายการ (รายการ)</th>
                        <th>จำนวนคนแทง (คน)</th>
                        <th>ยอดแทง (บาท)</th>
                        <th>ส่วนลด (บาท)</th>
                        <th>ยอดจ่าย (บาท)</th>
                        <th>กำไร/ขาดทุน (บาท)</th>
                      </tr>
                    </thead>

                    <tbody>
                      <% @bet_type_list.each do |k, v| %>

                      <tr>
                        <td><%= v %></td>
                        <td><%= @summary[k]['count'] %></td>
                        <td><%= [@summary['total']['user'], 0].max %></td>
                        <td><%= number_with_precision(@summary[k]['bet'], precision: 2, delimiter: ',') %></td>
                        <td><%= number_with_precision(@summary[k]['discount'], precision: 2, delimiter: ',') %></td>
                        <td><%= number_with_precision(@summary[k]['paid'], precision: 2, delimiter: ',') %></td>
                        <td><%= number_with_precision(@summary[k]['pnl'], precision: 2, delimiter: ',') %></td>
                      </tr>

                      <% end %>

                        <tr>
                          <td><strong>รวมทั้งหมด</strong></td>
                          <td><strong><%= @summary['total']['count'] %></strong></td>
                          <td><strong><%= [@summary['total']['user'], 0].max %></strong></td>
                          <td><strong><%= number_with_precision(@summary['total']['bet'], precision: 2, delimiter: ',') %></strong></td>
                          <td><strong><%= number_with_precision(@summary['total']['discount'], precision: 2, delimiter: ',') %></strong></td>
                          <td><strong><%= number_with_precision(@summary['total']['paid'], precision: 2, delimiter: ',') %></strong></td>
                          <td><strong><%= number_with_precision(@summary['total']['pnl'], precision: 2, delimiter: ',') %></strong></td>
                        </tr>
                    </tbody>

                  </table>


                  <hr />


                  <h5>รายการแทงทั้งหมด</h5>
                  <table id="transaction_table" class="table-sm table-striped table-responsive" data-toggle="datatables">
                    <thead>
                      <tr>
                        <th>ลำดับ</th>
                        <th>วันที่</th>
                        <th>ผู้ใช้งาน</th>
                        <th>ประเภท</th>
                        <th>เลข</th>
                        <th>แต้มต่อ</th>
                        <th>จำนวนเงิน</th>
                        <th>ส่วนลด</th>
                        <th>ยอดจ่าย</th>
                        <th>ยอดเงินคงเหลือ(ก่อนแทง)</th>
                        <th>ยอดเงินคงเหลือ(หลังแทง, ก่อนออกผลรางวัล)</th>
                        <th>สถานะ</th>
                        <th>ไอดีการแทง</th>
                      </tr>
                    </thead>
                    <tbody>

                      <% @transactions.each_with_index do |r, index| %>
                      <% cWin = r['status'] == 'ถูก' ? 'table-success' : '' %>
                      <tr class="<%= cWin %>">
                        <td><%= (index+1) %></td>
                        <td><span id="transaction_table_<%= index %>_created_at"></span></td>
                        <td><%= User.find(r['username']).username %></td>
                        <td><%= @bet_type['bet_type'][r['bet_type']]['name'] %></td>
                        <td><%= r['number'] %></td>
                        <td><%= r['odd'] %></td>
                        <td><%= number_with_precision(r['bet_value'], precision: 2, delimiter: ',') %></td>
                        <td><%= number_with_precision(r['bet_value']*r['discount']/100, precision: 2, delimiter: ',') %></td>
                        <td><%= number_with_precision(r['paid'], precision: 2, delimiter: ',') %></td>
                        <td><%= number_with_precision(r['money720808'], precision: 2, delimiter: ',') %></td>
                        <td><%= number_with_precision(r['money720808']-(1-r['discount']/100)*r['bet_value'], precision: 2, delimiter: ',') %></td>
                        <td><%= r['status'] %></td>
                        <td><%= r['_id'].to_str.last(6) %></td>
                      </tr>
                      <% end %>
                    </tbody>
                    <tfoot>
                      <tr>
                        <th>ลำดับ</th>
                        <th>วันที่</th>
                        <th>ผู้ใช้งาน</th>
                        <th>ประเภท</th>
                        <th>เลข</th>
                        <th>แต้มต่อ</th>
                        <th>จำนวนเงิน</th>
                        <th>ส่วนลด</th>
                        <th>ยอดจ่าย</th>
                        <th>ยอดเงินคงเหลือ(ก่อนแทง)</th>
                        <th>ยอดเงินคงเหลือ(หลังแทง, ก่อนออกผลรางวัล)</th>
                        <th>สถานะ</th>
                        <th>ไอดีการแทง</th>
                      </tr>
                    </tfoot>
                  </table>
                </div>
                <div class="tab-pane" id="3digits" aria-expanded="false">

                  <h5>3 หลัก</h5>
                  <table id="3digits_table" class="table-sm table-striped table-responsive" data-toggle="datatables">
                    <thead>
                      <tr>
                        <th>เลข</th>
                        <th>บน</th>
                        <th>โต๊ด</th>
                        <th>ล่าง</th>
                        <th>หน้า</th>
                      </tr>
                    </thead>
                    <tbody>

                      <% (0..999).each do |index| %>
                      <% number = "%.3d" % index %>

                      <tr>
                        <td><%= number %></td>
                        <td>
                          <span id="sum_<%= number %>_b31">0</span>
                        </td>
                        <td>
                          <span id="sum_<%= number %>_b32">0</span>
                        </td>
                        <td>
                          <span id="sum_<%= number %>_b33">0</span>
                        </td>
                        <td>
                          <span id="sum_<%= number %>_b34">0</span>
                        </td>

                      </tr>
                      <% end %>
                    </tbody>
                  </table>
                </div>
                <div class="tab-pane" id="2digits" aria-expanded="false">
                  <h5>2 หลัก</h5>
                  <table id="2digits_table" class="table-sm table-striped table-responsive" data-toggle="datatables">
                    <thead>
                      <tr>
                        <th>เลข</th>
                        <th>บน</th>
                        <th>ล่าง</th>
                      </tr>
                    </thead>
                    <tbody>

                      <% (0..99).each do |index| %>
                      <% number = "%.2d" % index %>

                      <tr>
                        <td><%= number %></td>
                        <td>
                          <span id="sum_<%= number %>_b21">0</span>
                        </td>
                        <td>
                          <span id="sum_<%= number %>_b22">0</span>
                        </td>

                      </tr>
                      <% end %>
                    </tbody>
                  </table>
                </div>
                <div class="tab-pane" id="1digits" aria-expanded="false">
                  <h5>1 หลัก</h5>
                  <table id="1digits_table" class="table-sm table-striped table-responsive" data-toggle="datatables">
                    <thead>
                      <tr>
                        <th>เลข</th>
                        <th>บน</th>
                        <th>ล่าง</th>
                      </tr>
                    </thead>
                    <tbody>

                      <% (0..9).each do |index| %>
                      <% number = index %>

                      <tr>
                        <td><%= number %></td>
                        <td>
                          <span id="sum_<%= number %>_b11">0</span>
                        </td>
                        <td>
                          <span id="sum_<%= number %>_b12">0</span>
                        </td>

                      </tr>
                      <% end %>
                    </tbody>
                  </table>
                </div>
              </div>
              <!-- /.tab-content -->
            </div>


          </div>
        </div>
      </div>
    </div>
  </div>
</main>


<script src="<%= root_url%>assets/js/admin/rounds_show.js"></script>