config/routes.rb
Rails.application.routes.draw do


  get 'pages/result'

  get 'products/laos'
  get 'products/thai'


  resources :bet_types
  get 'admin/index'
  get 'admin/rounds'
  get 'admin/requests'
  get 'admin/transactions'
  get 'admin/users'
  get 'admin/stats'
  get 'admin/notification'
  get 'admin/bypass'
  get 'admin/resetpwd'

  resources :transactions
  resources :rounds

  post 'rounds/calculate'
  post 'rounds/process1688'

  resources :requests do
    get 'confirm(.:format)' => 'requests#confirm'
    get 'cancel(.:format)' => 'requests#cancel'
  end
  get 'pages/index'
  get 'pages/faq'
  get 'pages/odd_table'
  root 'products#index'
  get 'products/thai'
  get 'products/laos'
  get 'products/index'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '*path' => redirect('/')
end

app/views/layouts/_footer.html.erb
<!-- FOOTER -->


<!--/ #wrapper -->
<!-- Scripts -->

<script src="<%= root_url%>assets/js/popper.min.js"></script>
<script src="<%= root_url%>assets/js/bootstrap.min.js"></script>
<script src="<%= root_url%>assets/js/metisMenu.min.js"></script>
<script src="<%= root_url%>assets/js/perfect-scrollbar.jquery.min.js"></script>
<script src="<%= root_url%>assets/js/sweetalert2.min.js"></script>
<script src="<%= root_url%>assets/js/jquery.knob.min.js"></script>
<script src="<%= root_url%>assets/vendors/theme-widgets/widgets.js"></script>
<script src="<%= root_url%>assets/js/moment.min.js"></script>
<script src="<%= root_url%>assets/js/jquery-ui.min.js"></script>
<script src="<%= root_url%>assets/js/clndr.min.js"></script>
<script src="<%= root_url%>assets/js/raphael.min.js"></script>
<script src="<%= root_url%>assets/js/jquery.dataTables.min.js"></script>
<script src="<%= root_url%>assets/js/jquery.toast.min.js"></script>
<script src="<%= root_url%>assets/js/bootstrap-datepicker.min.js"></script>
<script src="<%= root_url%>assets/js/bootstrap-clockpicker.min.js"></script>
<script src="<%= root_url%>assets/js/jquery.floatThead.min.js"></script>
<script src="<%= root_url%>assets/js/jquery.tabledit.min.js"></script>

<script src="<%= root_url%>assets/js/theme.js"></script>
<script src="<%= root_url%>assets/js/custom.js"></script>

app/views/layouts/_header.html.erb
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no">
<link rel="icon" type="image/png" sizes="16x16" href="<%= root_url%>assets/images/favicon.png">
<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

<!-- CSS -->

<link href="<%= root_url%>assets/vendors/material-icons/material-icons.css" rel="stylesheet" type="text/css">
<link href="https://fonts.googleapis.com/css?family=Nunito+Sans:400,600,700" rel="stylesheet" type="text/css">
<link href="https://fonts.googleapis.com/css?family=Roboto:300,400,400i,500,700" rel="stylesheet" type="text/css">
<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600" rel="stylesheet" type="text/css">
<link href="<%= root_url%>assets/css/bootstrap-clockpicker.min.css" rel="stylesheet" type="text/css">
<link href="<%= root_url%>assets/css/bootstrap-datepicker.min.css" rel="stylesheet" type="text/css">
<link href="<%= root_url%>assets/css/jquery.toast.min.css" rel="stylesheet" type="text/css">
<link href="<%= root_url%>assets/css/jquery.dataTables.min.css" rel="stylesheet" type="text/css">
<link href="<%= root_url%>assets/css/sweetalert2.min.css" rel="stylesheet" type="text/css">
<link href="<%= root_url%>assets/css/style.css" rel="stylesheet" type="text/css">
<link href="<%= root_url%>assets/css/custom.css" rel="stylesheet" type="text/css">
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
<!-- Head Libs -->
<script src="<%= root_url%>assets/js/jquery.min.js"></script>
<script src="<%= root_url%>assets/js/modernizr.min.js"></script>

app/views/layouts/_navbar.html.erb
<!-- HEADER & TOP NAVIGATION -->
<nav class="navbar">
  <!-- Logo Area -->
  <div class="navbar-header">
    <a href="<%= root_url %>" class="navbar-brand text-center">
      <img class="logo-expand" alt="" src="<%= root_url%>assets/images/logo-expand.png">
      <img class="logo-collapse" alt="" src="<%= root_url%>assets/images/logo-collapse.png">
      <!-- <p>OSCAR</p> -->
    </a>
  </div>
  <!-- /.navbar-header -->
  <!-- Left Menu & Sidebar Toggle -->
  <ul class="nav navbar-nav">
    <li class="sidebar-toggle">
      <a href="javascript:void(0)" class="ripple">
        <i class="material-icons list-icon">menu</i>
      </a>
    </li>
  </ul>
  <!-- /.navbar-left -->

  <div class="spacer"></div>

  <!-- /.navbar-right -->
  <ul class="nav navbar-nav" id="nav-user">
    <% if user_signed_in? %>
    <li>
      <div>

        <% if user_signed_in? && current_user.username == "168899" %>

        <span>เบอร์:</span>
        <%= current_user.username %><br>

      ฝาก: <span class="badge badge-pill bg-primary" id="wait_deposit"></span>
      ถอน: <span class="badge badge-pill bg-primary" id="wait_withdraw"></span>

      <% else %>
        <span>เบอร์:</span>
        <%= current_user.username %><br>
        <span>เงิน:</span>
        <%=  number_to_currency( current_user.money720808, unit: "฿", precision: 2 ) %>
        <input id="user_money" value="<%= current_user.money720808 %>" type="hidden">
        <% end %>
      </div>

    </li>
  <% else %>
    <li>
      <a href="<%= root_url %>users/sign_in">เข้าสู่ระบบ</a>
    </li>
    <% end %>
  </ul>
  <!-- /.navbar-right -->
</nav>
<!-- /.navbar -->
<div class="content-wrapper">
  <!-- SIDEBAR -->
  <!-- Begin Admin Panel -->
  <% if user_signed_in? && current_user.username == "168899" %>

  <aside class="site-sidebar clearfix">
    <nav class="sidebar-nav">
      <ul class="nav in side-menu">
        <li class="menu-item">
          <a href="<%= root_path %>">
            <i class="list-icon material-icons">home</i>
            <span class="hide-menu">หน้าหลัก</span>
          </a>
        </li>
        <li class="menu-item">
          <a href="<%= admin_requests_path %>">
            <i class="list-icon material-icons">shopping_cart</i>
            <span class="hide-menu">รายการฝาก/ถอน</span>
          </a>
        </li>
        <li class="menu-item">
          <a href="<%= rounds_path %>">
            <i class="list-icon material-icons">payment</i>
            <span class="hide-menu">รอบหวยทั้งหมด</span>
          </a>
        </li>
        <li class="menu-item">
          <a href="<%= rounds_path %>/new">
            <i class="list-icon material-icons">lightbulb_outline</i>
            <span class="hide-menu">เพิ่มรอบหวย</span>
          </a>
        </li>
        <li class="menu-item">
          <a href="<%= bet_types_path %>">
            <i class="list-icon material-icons">help_outline</i>
            <span class="hide-menu">ตารางการจ่าย</span>
          </a>
        </li>
        <li class="menu-item">
          <a href="<%= admin_users_path %>">
            <i class="list-icon material-icons">help_outline</i>
            <span class="hide-menu">ผู้ใช้งานทั้งหมด</span>
          </a>
        </li>
        <li class="menu-item">
          <a href="<%= destroy_user_session_path %>" method="delete">
            <i class="list-icon material-icons">face</i>
            <span class="hide-menu">ออกจากระบบ</span>
          </a>
        </li>
      </ul>
      </nav>
      <!-- /.sidebar-nav -->
    </aside>
    <!-- end admin panel -->
  <% else %>
    <aside class="site-sidebar clearfix">
      <nav class="sidebar-nav">
        <ul class="nav in side-menu">
          <li class="menu-item">
            <a href="<%= root_path %>">
              <i class="list-icon material-icons">home</i>
              <span class="hide-menu">หน้าหลัก</span>
            </a>
          </li>
          <li class="menu-item">
            <a href="<%= root_path %>">
              <i class="list-icon material-icons">shopping_cart</i>
              <span class="hide-menu">ซื้อหวย</span>
            </a>
              <ul class="list-unstyled sub-menu">
                <li>
                  <a href="<%= root_path %>products/laos">หวยลาว</a>
                </li>
                <li>
                  <a href="<%= root_path %>products/thai">หวยไทย</a>
                </li>

              </ul>

          </li>
          <li class="menu-item">
            <a href="<%= transactions_path %>">
              <i class="list-icon material-icons">receipt</i>
              <span class="hide-menu">รายการแทง</span>
            </a>
          </li>
          <li class="menu-item">
            <a href="<%= requests_path %>">
              <i class="list-icon material-icons">payment</i>
              <span class="hide-menu">เติมเงิน</span>
            </a>
          </li>
          <li class="menu-item">
            <a href="<%= pages_odd_table_path %>">
              <i class="list-icon material-icons">trending_up</i>
              <span class="hide-menu">อัตราจ่าย</span>
            </a>
          </li>
          <li class="menu-item">
            <a href="<%= pages_result_path %>">
              <i class="list-icon material-icons">lightbulb_outline</i>
              <span class="hide-menu">เลขที่ออก</span>
            </a>
          </li>
          <li class="menu-item">
            <a href="<%= pages_faq_path %>">
              <i class="list-icon material-icons">help_outline</i>
              <span class="hide-menu">คำถามที่พบบ่อย</span>
            </a>
          </li>

          <% if 1 == 1 %>
          <li class="menu-item-has-children">
            <a href="javascript:void(0);">
              <i class="list-icon material-icons">person</i>
              <span class="hide-menu">ผู้ใช้งาน</span>
            </a>
            <ul class="list-unstyled sub-menu">
              <% if user_signed_in? %>
              <li>
                <%= link_to 'แก้ไขข้อมูล', edit_user_registration_path %>
              </li>
              <li>
                <%= link_to 'ออกจากระบบ', destroy_user_session_path, method: :delete %>
              </li>
            <% else %>
              <li>
                <a href="<%= root_url %>users/sign_in">เข้าสู่ระบบ</a>
              </li>
              <li>
                <%= link_to 'สมัครสมาชิก', new_user_registration_path %>
              </li>
              <% end %>
            </ul>
          </li>

          <% end %>
          <% if user_signed_in? && current_user.username == "168899" %>
          <li class="menu-item-has-children">
            <a href="javascript:void(0);">
              <i class="list-icon material-icons">face</i>
              <span class="hide-menu">ผู้ดูแลระบบ</span>
            </a>
            <ul class="list-unstyled sub-menu">
              <li>
                <%= link_to 'รายการฝาก/ถอนเงิน', admin_requests_path %>
              </li>
              <li>
                <%= link_to 'รอบหวยทั้งหมด', rounds_path %>
              </li>
              <li>
                <%= link_to 'เพิ่มรอบหวย', (rounds_path+"/new") %>
              </li>
              <li>
                <%= link_to 'ตารางการจ่าย', bet_types_path %>
              </li>
              <li>
                <%= link_to 'ออกจากระบบ', destroy_user_session_path, method: :delete %>
              </li>

            </ul>
          </li>
          <% end %>
        </ul>
        <!-- /.side-menu -->
      </nav>
      <!-- /.sidebar-nav -->
    </aside>
    <!-- /.site-sidebar -->

    <% end %>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="th" prefix="og: http://ogp.me/ns#">

<head>
  <!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-K3BDVJ8');</script>
<!-- End Google Tag Manager -->
    <title>Lot1688.com - หวยรวยรวย, หวยลาว, หวยไทย</title>
    <%= render "layouts/header" %>

</head>

<body class="header-centered sidebar-horizontal">
  <!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-K3BDVJ8"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->
    <div id="wrapper" class="wrapper">
        <%= render "layouts/navbar" %>
        <%= yield %>
    </div>
    <!-- /.content-wrapper -->
    <%= render "layouts/footer" %>
    <!-- WhatsHelp.io widget -->
<script type="text/javascript">
    (function () {
        var options = {
            line: "//line.me/ti/p/@osd1030j", // Line QR code URL
            company_logo_url: "//lot1688.com/assets/images/lot1688_square_logo.jpg", // URL of company logo (png, jpg, gif)
            greeting_message: "Lot1688.com หวยรวยรวย ยินดีต้อนรับค่ะ เพื่อความสะดวก รบกวนแอดไลน์ด้วยค่ะ☀☀☀", // Text of greeting message
            call_to_action: "รบกวนแอดไลน์ด้วยค่ะ ☀☀☀", // Call to action
            position: "right", // Position may be 'right' or 'left'
        };
        var proto = document.location.protocol, host = "whatshelp.io", url = proto + "//static." + host;
        var s = document.createElement('script'); s.type = 'text/javascript'; s.async = true; s.src = url + '/widget-send-button/js/init.js';
        s.onload = function () { WhWidgetSendButton.init(host, proto, options); };
        var x = document.getElementsByTagName('script')[0]; x.parentNode.insertBefore(s, x);
    })();
</script>
<!-- /WhatsHelp.io widget -->
</body>

</html>